name             'solr'
maintainer       'Álvaro Faúndez'
maintainer_email 'alvaro@faundez.net'
license          'All rights reserved'
description      'Installs/Configures solr'
long_description 'Installs/Configures solr'
version          '0.1.2'

depends 'tar', '~> 0.7.0'
depends 'java', '~> 1.35.0'
